#! /usr/bin/env python3
# -*- coding: UTF-8 -*-
# Powerful client of furyTerminal

import sys
import os


def sh(command):
    os.system(command)


def runServer():
    sh('python ./manage.py runserver 0:8000')

def testModule():
    pass

def makeMigrationMigrate():
    sh('''
    python ./manage.py makemigrations
    python ./manage.py migrate
    ''')


command = {
    'default': runServer,
    'r': runServer,
    't': testModule,
    'm': makeMigrationMigrate
}

main = command[sys.argv[1] if len(sys.argv) > 1 else 'default']
main()
