#! /usr/bin/env python3
# -*- coding: UTF-8 -*-
# Powerful client of furyTerminal

import os
import sys


def sh(command):
    os.system(command)


def runServer():
    sh('''
    python ./manage.py runserver 0:8000 >log/server.log 2>&1 &
    python ./record.py 1>log/record.log 2>&1 &
    ''')


def testModule():
    pass


def makeMigrationMigrate():
    sh('''
    python ./manage.py makemigrations
    python ./manage.py migrate
    ''')


def install():
    """
    install necessary packages
    """
    sh('''
    sudo apt install bc -y
    sudo apt install python3 python3-dev -y
    sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 1
    sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
    pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
    pip3 install django
    pip3 install python-can
    pip3 install mysqlclient
    sudo apt install mariadb-server mariadb-client -y
    ''')


def config():
    """
    setup autorun configurations
    """
    if not os.path.exists(os.path.expanduser('~/.config/autostart/')):
        os.mkdir(os.path.expanduser('~/.config/autostart/'))
    sh('cp -f config/oncar.desktop ~/.config/autostart/')
    if not os.path.exists('/etc/systemd/system/'):
        os.mkdir('/etc/systemd/system/')
    sh('''
    sudo cp -f config/furyTerminal.service /etc/systemd/system/
    sudo systemctl enable furyTerminal.service
    ''')


command = {
    'default': runServer,
    'r': runServer,
    't': testModule,
    'm': makeMigrationMigrate,
    'install': install,
    'config': config,
}

# change cwd first
os.chdir(sys.path[0])
main = command[sys.argv[1] if len(sys.argv) > 1 else 'default']
main()
