# Generated by Django 2.2.7 on 2019-11-13 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='AIRFlag',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
