# Generated by Django 2.1.7 on 2019-03-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncar', '0002_auto_20190322_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speed',
            name='speed_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
