# Generated by Django 2.2.5 on 2019-10-31 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oncar', '0003_auto_20190322_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('acReliableFlag', models.CharField(max_length=20)),
                ('acBrReliableFlag', models.CharField(max_length=20)),
                ('startFlag', models.CharField(max_length=20)),
                ('runFlag', models.CharField(max_length=20)),
                ('driveReadyFlag', models.CharField(max_length=20)),
                ('SafetyFlag', models.CharField(max_length=20)),
                ('brFlag', models.CharField(max_length=20)),
                ('zfAllowFlag', models.CharField(max_length=20)),
                ('ycAllowFlag', models.CharField(max_length=20)),
                ('acFinal', models.CharField(max_length=20)),
                ('brFinal', models.CharField(max_length=20)),
                ('finalSendTorque', models.CharField(max_length=20)),
                ('gear', models.CharField(max_length=20)),
                ('rotateSpeed', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=20)),
                ('mcMessage1', models.CharField(max_length=20)),
                ('mcMessage2', models.CharField(max_length=20)),
                ('mcuTemp', models.CharField(max_length=20)),
                ('motorTemp', models.CharField(max_length=20)),
                ('dcMainVoltage', models.CharField(max_length=20)),
                ('dcMainCurrent', models.CharField(max_length=20)),
                ('acCurrent', models.CharField(max_length=20)),
                ('power', models.CharField(max_length=20)),
                ('batVoltage', models.CharField(max_length=20)),
                ('batCurrent', models.CharField(max_length=20)),
                ('batSoc', models.CharField(max_length=20)),
                ('batMaxTemp', models.CharField(max_length=20)),
                ('batMaxCellVolt', models.CharField(max_length=20)),
            ],
        ),
    ]
